### ISSUE TITLE
Django Apps (Modules) Completion Tracker

### ISSUE THREAD

**Issue by donovancham** [ICT2x01-p2-4/ICT2x01-p2-4#34]
- [x] Identity selection and auth
- [x] Initiate Connection
- [x] Student Home Page
- [x] Teacher Home Page
- [x] Challenge (selectchallenge, createchallenge)
- [x] Coding Page
- [x] Connection
- [x] Dashboard
- [x] Tutorial
- [ ] Logging (view past log)
